project:
  type: website

website:
  title: "Cursos 0 Geología"
  back-to-top-navigation: true

format:
  html:
    theme: sandstone
    fontsize: 1.2em
    toc: true
    sidebar: false

  page-footer: 
    right: Made with [Quarto](https://quarto.org/)
    #right: "Maintenance: the organizers"

