---
title: Cursos 0 Geología
subtitle: Facultad de Ciencias, Universidad de Granada
title-block-banner: true
toc: false
page-layout: full
---

Curso cero de Geología para la Facultad de Ciencias de la Universidad de Granada. Puedes encontrar otros cursos cero de nuestro centro en este [enlace](https://cursos-0-fc-ugr.github.io/).

Material elaborado por Claudio Marchesi, profesor del Departamento de Mineralogía y Petrología, José Vicente Pérez Peña, profesor del Departamento de Geodinámica y Gonzalo Jiménez Moreno, profesor del Departamento de Estratigrafía y Paleontología de la Universidad de Granada, para el Curso Cero de la UGR.

Este repositorio se puede visitar en [GitHub pages](https://github.com/dblanco-sudo/Geologia/).

Para esta edición se han actualizado los contenidos y adaptado a la LOMLOE. La versión anterior está disponible en este [enlace](https://dblanco-sudo.github.io/Geologia/Curso_old/DEADME.qmd).



## Contenidos

1. [Tema 1. Fuentes de información y métodos en Geología](Tema1/Tema1.html)
1. [Tema 2. La tectónica de placas](Tema2/Tema2.html)
1. [Tema 3. Procesos geológicos internos](Tema3/Tema3.html)
1. [Tema 4. Procesos geológicos externos](Tema4/Tema4.html)
1. [Tema 5. Minerales, los componentes de las rocas](Tema5/Tema5.html)
1. [Tema 6. Rocas ígneas, sedimentarias y metamórficas](Tema6/Tema6.html)
1. [Tema 7. Historia de la Tierra y la vida](Tema7/Tema7.html)
1. [Tema 8. Recursos geológicos](Tema8/Tema8.html)
